### ISSUE TITLE
Should be contributed by every participant #SWoC20

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#47]
Update readme
Create different segment of installation of project, like installation of software required to carry on with backend, frontend part prerequistives and process. 
Make the issue you're working on documented so that the next person who will work on it get familiar.

**Comment by nilisha-jais** [comment]
I can work on it!!

**Comment by preeti13456** [comment]
Great. But the work is alot can you handle that. And it must be efficient.

**Comment by fatmab2809** [comment]
Can I work on this issue?

**Comment by preeti13456** [comment]
Sure

**Comment by preeti13456** [comment]
Update?

**Comment by fatmab2809** [comment]
Actually my exams are going on, so I'm not getting much time to work on it. But i will try to finish it in a week

**Comment by vismitap** [comment]
Hey! Can I work on this issue?

**Comment by preeti13456** [comment]
Sure

**Comment by vismitap** [comment]
Thanks for assigning! Can I contact you on slack personally?

**Comment by preeti13456** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vismitap** [comment]
Having some issues with the setting up of project dependencies! 
I got the `Error: could not find a version that satisfies the requirement psycopg2 == 2.8.5` with `python3` version.
It is suggesting to `pip install psycopg2-binary` instead. 
Searched a lot for a solution and came to know that we should be using <2.8.5 or 2.8.6.  Please refer [this](https://github.com/psycopg/psycopg2/issues/1075)

Because of the` psycopg2` package the other modules after it in requirements.txt are not getting installed by running the command `pip install -r requirements.txt`. I guess most of the contributors would be using the latest python version ie: python3 so they might face a lot of difficulties to get started with project.

Should I edit the` psycopg2 == 2.8.5` and upgrade to` psycopg2 == 2.8.6`??

**Comment by preeti13456** [comment]
Use the upgraded version as its preferred as it will work will  the lower version as well

**Comment by vismitap** [comment]
Okie thanks! Will edit in the requirements.txt as well then 👍

**Comment by vismitap** [comment]
Hey! I have raised a PR #69. Please review and suggest changes if any.
